// --- BEGIN AUTO-GENERATED FILE ---
//
// @IconsVersion: 1.0.0-alpha5
// @Generated: 2020-07-15T16:57:43.043Z
//
// This file is generated on each build. Do not edit this file!
/*
import Vue from 'vue'
import { BvComponent } from '../'

// --- BootstrapVue custom icons ---

export declare class BIconBlank extends BvComponent {}

// --- Bootstrap Icons ---

export declare class BIconAlarm extends BvComponent {}
*/

// TODO: the auto generation of this file has to be implemented to enable exports of single icons
