// --- BEGIN AUTO-GENERATED FILE ---
//
// This file is auto generated on each build. Do not edit this file!
// Run the necessary scripts defined in package.json to generate this file.

import { makeIcon } from "./helpers/make-icon";

export const AnxIcon110LKWTransport = makeIcon(
  "110LKWTransport",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIcon24h = makeIcon(
  "24h",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIcon3d = makeIcon(
  "3d",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAiKuenstlicheintelligenz = makeIcon(
  "AiKuenstlicheintelligenz",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAlexa = makeIcon(
  "Alexa",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAnderesWeiteresTeil = makeIcon(
  "AnderesWeiteresTeil",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAndroid = makeIcon(
  "Android",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAnexiaLogo = makeIcon(
  "AnexiaLogo",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAnexia = makeIcon(
  "Anexia",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconApp = makeIcon(
  "App",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconApple = makeIcon(
  "Apple",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconArbeitBuero = makeIcon(
  "ArbeitBuero",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconArrowGreenBottom = makeIcon(
  "ArrowGreenBottom",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconArrowRedBottom = makeIcon(
  "ArrowRedBottom",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAtSign = makeIcon(
  "AtSign",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconAuszeichnung = makeIcon(
  "Auszeichnung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconBarcode = makeIcon(
  "Barcode",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconBildFoto = makeIcon(
  "BildFoto",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconBlockchain = makeIcon(
  "Blockchain",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCardboardVrBrilleSmartphone = makeIcon(
  "CardboardVrBrilleSmartphone",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCardboardVrBrille = makeIcon(
  "CardboardVrBrille",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCheckGreen = makeIcon(
  "CheckGreen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCheckWhite = makeIcon(
  "CheckWhite",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCheck = makeIcon(
  "Check",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCloudStorage = makeIcon(
  "CloudStorage",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCloud = makeIcon(
  "Cloud",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCloudservicesHosting = makeIcon(
  "CloudservicesHosting",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconConnections = makeIcon(
  "Connections",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconController = makeIcon(
  "Controller",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconCopy = makeIcon(
  "Copy",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDashboardEchtzeitMonitor = makeIcon(
  "DashboardEchtzeitMonitor",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDatenbank = makeIcon(
  "Datenbank",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDevices = makeIcon(
  "Devices",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDns = makeIcon(
  "Dns",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDokument = makeIcon(
  "Dokument",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDollar = makeIcon(
  "Dollar",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDownload = makeIcon(
  "Download",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconDsl = makeIcon(
  "Dsl",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconESim = makeIcon(
  "ESim",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconEingabe = makeIcon(
  "Eingabe",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconEins = makeIcon(
  "Eins",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconEinstellungenVerwaltung = makeIcon(
  "EinstellungenVerwaltung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconError = makeIcon(
  "Error",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconEuro = makeIcon(
  "Euro",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconExperimentierfreudig = makeIcon(
  "Experimentierfreudig",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconFabrik = makeIcon(
  "Fabrik",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconFirmenautoAuto = makeIcon(
  "FirmenautoAuto",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconFlexibilitaet = makeIcon(
  "Flexibilitaet",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconFlexibleArbeitszeitenTiming = makeIcon(
  "FlexibleArbeitszeitenTiming",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconFolder = makeIcon(
  "Folder",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconForschungEntwicklung = makeIcon(
  "ForschungEntwicklung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconFotoapparat = makeIcon(
  "Fotoapparat",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconFramework = makeIcon(
  "Framework",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconGabelstapler = makeIcon(
  "Gabelstapler",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconGefahrenWarnung = makeIcon(
  "GefahrenWarnung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconGenericautomation = makeIcon(
  "Genericautomation",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconHerz = makeIcon(
  "Herz",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconHomeoffice = makeIcon(
  "Homeoffice",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconIdee = makeIcon(
  "Idee",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconInformation = makeIcon(
  "Information",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconInstallation = makeIcon(
  "Installation",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconInterdisziplinaer = makeIcon(
  "Interdisziplinaer",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconIp = makeIcon(
  "Ip",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconKalender = makeIcon(
  "Kalender",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconKontaktTelefonTelekommunikation = makeIcon(
  "KontaktTelefonTelekommunikation",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconKonzept = makeIcon(
  "Konzept",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconKunde = makeIcon(
  "Kunde",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconKunden = makeIcon(
  "Kunden",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconLaden = makeIcon(
  "Laden",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconLastverteilung = makeIcon(
  "Lastverteilung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconLike = makeIcon(
  "Like",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconLoeschen = makeIcon(
  "Loeschen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMailKontakt = makeIcon(
  "MailKontakt",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMassgeschneiderteIndividuelleLoesungen = makeIcon(
  "MassgeschneiderteIndividuelleLoesungen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMbaas = makeIcon(
  "Mbaas",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMicrocontroller = makeIcon(
  "Microcontroller",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMitarbeiterevents = makeIcon(
  "Mitarbeiterevents",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMobileEntwicklung = makeIcon(
  "MobileEntwicklung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMonitoring = makeIcon(
  "Monitoring",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconMusik = makeIcon(
  "Musik",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconNetzwerk = makeIcon(
  "Netzwerk",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconOeffentlicherNahverkehr = makeIcon(
  "OeffentlicherNahverkehr",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconOffline = makeIcon(
  "Offline",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconOnlineshopWarenkorb = makeIcon(
  "OnlineshopWarenkorb",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPaket = makeIcon(
  "Paket",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconParkplatz = makeIcon(
  "Parkplatz",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPartyProjektabschluss = makeIcon(
  "PartyProjektabschluss",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPdf = makeIcon(
  "Pdf",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPfeilLinksKlein = makeIcon(
  "PfeilLinksKlein",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPfeilLinks = makeIcon(
  "PfeilLinks",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPfeilOben = makeIcon(
  "PfeilOben",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPfeilRechtsKlein = makeIcon(
  "PfeilRechtsKlein",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPfeilRechts = makeIcon(
  "PfeilRechts",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPfeilRunter = makeIcon(
  "PfeilRunter",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPflichtenheft = makeIcon(
  "Pflichtenheft",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPlatform = makeIcon(
  "Platform",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconPraesentation = makeIcon(
  "Praesentation",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconProjektablauf = makeIcon(
  "Projektablauf",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconProjektmanagementCheckliste = makeIcon(
  "ProjektmanagementCheckliste",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconRedundant = makeIcon(
  "Redundant",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSatellit = makeIcon(
  "Satellit",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSchluessel = makeIcon(
  "Schluessel",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconScrum = makeIcon(
  "Scrum",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSeoSemCrawler = makeIcon(
  "SeoSemCrawler",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconServerVeerbunden = makeIcon(
  "ServerVeerbunden",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconServiceprovider = makeIcon(
  "Serviceprovider",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSharing = makeIcon(
  "Sharing",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconShop = makeIcon(
  "Shop",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSicherheitFirewall = makeIcon(
  "SicherheitFirewall",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSignal = makeIcon(
  "Signal",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSkalierbar = makeIcon(
  "Skalierbar",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSmartTv = makeIcon(
  "SmartTv",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSmartWatch = makeIcon(
  "SmartWatch",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSmarthome = makeIcon(
  "Smarthome",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSoftwareentwicklungCode = makeIcon(
  "SoftwareentwicklungCode",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSpieleUndSpass = makeIcon(
  "SpieleUndSpass",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSprechblasen = makeIcon(
  "Sprechblasen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconStandortUnternehmenssitz = makeIcon(
  "StandortUnternehmenssitz",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconStartUp = makeIcon(
  "StartUp",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconStatistikAnalysen = makeIcon(
  "StatistikAnalysen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconStern = makeIcon(
  "Stern",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconStorageBackup = makeIcon(
  "StorageBackup",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconStromEnergie = makeIcon(
  "StromEnergie",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSuchen = makeIcon(
  "Suchen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconSupportMitarbeiter = makeIcon(
  "SupportMitarbeiter",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconTasse = makeIcon(
  "Tasse",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconTeam = makeIcon(
  "Team",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconTechnischerSupport = makeIcon(
  "TechnischerSupport",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconTextdokument = makeIcon(
  "Textdokument",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconTextdokumentFragezeichen = makeIcon(
  "TextdokumentFragezeichen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconTextdokumentRufzeichen = makeIcon(
  "TextdokumentRufzeichen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconUpload = makeIcon(
  "Upload",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconUserProfil = makeIcon(
  "UserProfil",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVerbundeneServerBlade = makeIcon(
  "VerbundeneServerBlade",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVerlautbarungWichtigeNewsPressemitteilung = makeIcon(
  "VerlautbarungWichtigeNewsPressemitteilung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVerpflegungMittagspauseEssen = makeIcon(
  "VerpflegungMittagspauseEssen",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVerschluesselung = makeIcon(
  "Verschluesselung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVideo = makeIcon(
  "Video",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVierenBugs = makeIcon(
  "VierenBugs",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVirtualisierung = makeIcon(
  "Virtualisierung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVollbildVerschieben = makeIcon(
  "VollbildVerschieben",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconVr = makeIcon(
  "Vr",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWachstumUmsatz = makeIcon(
  "WachstumUmsatz",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWarning = makeIcon(
  "Warning",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWebdesign = makeIcon(
  "Webdesign",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWebentwicklung = makeIcon(
  "Webentwicklung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWeiterbildung = makeIcon(
  "Weiterbildung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWeltweiteInfrastrukturWeltweiteVernetzungGlobalWwc = makeIcon(
  "WeltweiteInfrastrukturWeltweiteVernetzungGlobalWwc",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWhiteLabel = makeIcon(
  "WhiteLabel",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWidgets = makeIcon(
  "Widgets",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWindows = makeIcon(
  "Windows",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconWlan = makeIcon(
  "Wlan",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconZeitungMedienNews = makeIcon(
  "ZeitungMedienNews",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconZertifikat = makeIcon(
  "Zertifikat",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

export const AnxIconZielMarkierung = makeIcon(
  "ZielMarkierung",
  "<defs><style>  .cls-1 {	fill: none;	stroke: #77bc1f;	stroke-miterlimit: 10;	stroke-width: 7.5px;  }</style></defs><title>073-Euro</title><g><circle class='cls-1' cx='129' cy='129' r='125'/><g>  <line class='cls-1' x1='59.62' y1='113.75' x2='143.14' y2='113.75'/>  <line class='cls-1' x1='59.62' y1='140.43' x2='143.14' y2='140.43'/>  <path class='cls-1' d='M167.44,70.58a63.62,63.62,0,1,0,0,116.86'/></g></g>"
);

// --- END AUTO-GENERATED FILE ---
