// --- BEGIN AUTO-GENERATED FILE ---
//
// This file is auto generated on each build. Do not edit this file!
// Run the necessary scripts defined in package.json to generate this file.

import Vue from "vue";

export declare class AnxIcon24h extends Vue {}

export declare class AnxIcon3d extends Vue {}

export declare class AnxIconAiKuenstlicheintelligenz extends Vue {}

export declare class AnxIconAlexa extends Vue {}

export declare class AnxIconAnderesWeiteresTeil extends Vue {}

export declare class AnxIconAndroid extends Vue {}

export declare class AnxIconAnexiaStamp extends Vue {}

export declare class AnxIconAnexia extends Vue {}

export declare class AnxIconApp extends Vue {}

export declare class AnxIconApple extends Vue {}

export declare class AnxIconArbeitBuero extends Vue {}

export declare class AnxIconArrowGreenBottom extends Vue {}

export declare class AnxIconArrowRedBottom extends Vue {}

export declare class AnxIconAtSign extends Vue {}

export declare class AnxIconAuszeichnung extends Vue {}

export declare class AnxIconBarcode extends Vue {}

export declare class AnxIconBildFoto extends Vue {}

export declare class AnxIconBlockchain extends Vue {}

export declare class AnxIconCardboardVrBrilleSmartphone extends Vue {}

export declare class AnxIconCardboardVrBrille extends Vue {}

export declare class AnxIconCheckGreen extends Vue {}

export declare class AnxIconCheckWhite extends Vue {}

export declare class AnxIconCheck extends Vue {}

export declare class AnxIconCloudStorage extends Vue {}

export declare class AnxIconCloud extends Vue {}

export declare class AnxIconCloudservicesHosting extends Vue {}

export declare class AnxIconConnections extends Vue {}

export declare class AnxIconController extends Vue {}

export declare class AnxIconCopy extends Vue {}

export declare class AnxIconDashboardEchtzeitMonitor extends Vue {}

export declare class AnxIconDatenbank extends Vue {}

export declare class AnxIconDevices extends Vue {}

export declare class AnxIconDns extends Vue {}

export declare class AnxIconDokument extends Vue {}

export declare class AnxIconDollar extends Vue {}

export declare class AnxIconDownload extends Vue {}

export declare class AnxIconDsl extends Vue {}

export declare class AnxIconESim extends Vue {}

export declare class AnxIconEingabe extends Vue {}

export declare class AnxIconEins extends Vue {}

export declare class AnxIconEinstellungenVerwaltung extends Vue {}

export declare class AnxIconError extends Vue {}

export declare class AnxIconEuro extends Vue {}

export declare class AnxIconExperimentierfreudig extends Vue {}

export declare class AnxIconFabrik extends Vue {}

export declare class AnxIconFirmenautoAuto extends Vue {}

export declare class AnxIconFlexibilitaet extends Vue {}

export declare class AnxIconFlexibleArbeitszeitenTiming extends Vue {}

export declare class AnxIconFolder extends Vue {}

export declare class AnxIconForschungEntwicklung extends Vue {}

export declare class AnxIconFotoapparat extends Vue {}

export declare class AnxIconFramework extends Vue {}

export declare class AnxIconGabelstapler extends Vue {}

export declare class AnxIconGefahrenWarnung extends Vue {}

export declare class AnxIconGenericautomation extends Vue {}

export declare class AnxIconHerz extends Vue {}

export declare class AnxIconHomeoffice extends Vue {}

export declare class AnxIconIdee extends Vue {}

export declare class AnxIconInformation extends Vue {}

export declare class AnxIconInstallation extends Vue {}

export declare class AnxIconInterdisziplinaer extends Vue {}

export declare class AnxIconIp extends Vue {}

export declare class AnxIconKalender extends Vue {}

export declare class AnxIconKontaktTelefonTelekommunikation extends Vue {}

export declare class AnxIconKonzept extends Vue {}

export declare class AnxIconKunde extends Vue {}

export declare class AnxIconKunden extends Vue {}

export declare class AnxIconLaden extends Vue {}

export declare class AnxIconLastverteilung extends Vue {}

export declare class AnxIconLike extends Vue {}

export declare class AnxIconLKWTransport extends Vue {}

export declare class AnxIconLoeschen extends Vue {}

export declare class AnxIconMailKontakt extends Vue {}

export declare class AnxIconMassgeschneiderteIndividuelleLoesungen extends Vue {}

export declare class AnxIconMbaas extends Vue {}

export declare class AnxIconMicrocontroller extends Vue {}

export declare class AnxIconMitarbeiterevents extends Vue {}

export declare class AnxIconMobileEntwicklung extends Vue {}

export declare class AnxIconMonitoring extends Vue {}

export declare class AnxIconMusik extends Vue {}

export declare class AnxIconNetzwerk extends Vue {}

export declare class AnxIconOeffentlicherNahverkehr extends Vue {}

export declare class AnxIconOffline extends Vue {}

export declare class AnxIconOnlineshopWarenkorb extends Vue {}

export declare class AnxIconPaket extends Vue {}

export declare class AnxIconParkplatz extends Vue {}

export declare class AnxIconPartyProjektabschluss extends Vue {}

export declare class AnxIconPdf extends Vue {}

export declare class AnxIconPfeilLinksKlein extends Vue {}

export declare class AnxIconPfeilLinks extends Vue {}

export declare class AnxIconPfeilOben extends Vue {}

export declare class AnxIconPfeilRechtsKlein extends Vue {}

export declare class AnxIconPfeilRechts extends Vue {}

export declare class AnxIconPfeilRunter extends Vue {}

export declare class AnxIconPflichtenheft extends Vue {}

export declare class AnxIconPlatform extends Vue {}

export declare class AnxIconPraesentation extends Vue {}

export declare class AnxIconProjektablauf extends Vue {}

export declare class AnxIconProjektmanagementCheckliste extends Vue {}

export declare class AnxIconRedundant extends Vue {}

export declare class AnxIconSatellit extends Vue {}

export declare class AnxIconSchluessel extends Vue {}

export declare class AnxIconScrum extends Vue {}

export declare class AnxIconSeoSemCrawler extends Vue {}

export declare class AnxIconServerVeerbunden extends Vue {}

export declare class AnxIconServiceprovider extends Vue {}

export declare class AnxIconSharing extends Vue {}

export declare class AnxIconShop extends Vue {}

export declare class AnxIconSicherheitFirewall extends Vue {}

export declare class AnxIconSignal extends Vue {}

export declare class AnxIconSkalierbar extends Vue {}

export declare class AnxIconSmartTv extends Vue {}

export declare class AnxIconSmartWatch extends Vue {}

export declare class AnxIconSmarthome extends Vue {}

export declare class AnxIconSoftwareentwicklungCode extends Vue {}

export declare class AnxIconSpieleUndSpass extends Vue {}

export declare class AnxIconSprechblasen extends Vue {}

export declare class AnxIconStandortUnternehmenssitz extends Vue {}

export declare class AnxIconStartUp extends Vue {}

export declare class AnxIconStatistikAnalysen extends Vue {}

export declare class AnxIconStern extends Vue {}

export declare class AnxIconStorageBackup extends Vue {}

export declare class AnxIconStromEnergie extends Vue {}

export declare class AnxIconSuchen extends Vue {}

export declare class AnxIconSupportMitarbeiter extends Vue {}

export declare class AnxIconTasse extends Vue {}

export declare class AnxIconTeam extends Vue {}

export declare class AnxIconTechnischerSupport extends Vue {}

export declare class AnxIconTextdokument extends Vue {}

export declare class AnxIconTextdokumentFragezeichen extends Vue {}

export declare class AnxIconTextdokumentRufzeichen extends Vue {}

export declare class AnxIconUpload extends Vue {}

export declare class AnxIconUserProfil extends Vue {}

export declare class AnxIconVerbundeneServerBlade extends Vue {}

export declare class AnxIconVerlautbarungWichtigeNewsPressemitteilung extends Vue {}

export declare class AnxIconVerpflegungMittagspauseEssen extends Vue {}

export declare class AnxIconVerschluesselung extends Vue {}

export declare class AnxIconVideo extends Vue {}

export declare class AnxIconVierenBugs extends Vue {}

export declare class AnxIconVirtualisierung extends Vue {}

export declare class AnxIconVollbildVerschieben extends Vue {}

export declare class AnxIconVr extends Vue {}

export declare class AnxIconWachstumUmsatz extends Vue {}

export declare class AnxIconWarningSmall extends Vue {}

export declare class AnxIconWarning extends Vue {}

export declare class AnxIconWebdesign extends Vue {}

export declare class AnxIconWebentwicklung extends Vue {}

export declare class AnxIconWeiterbildung extends Vue {}

export declare class AnxIconWeltweiteInfrastrukturWeltweiteVernetzungGlobalWwc extends Vue {}

export declare class AnxIconWhiteLabel extends Vue {}

export declare class AnxIconWidgets extends Vue {}

export declare class AnxIconWindows extends Vue {}

export declare class AnxIconWlan extends Vue {}

export declare class AnxIconX extends Vue {}

export declare class AnxIconZeitungMedienNews extends Vue {}

export declare class AnxIconZertifikat extends Vue {}

export declare class AnxIconZielMarkierung extends Vue {}

// --- END AUTO-GENERATED FILE ---
